# Generated by Django 3.2.18 on 2024-05-12 10:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('College_ID', models.AutoField(primary_key=True, serialize=False)),
                ('College_Name', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Password', models.CharField(max_length=50)),
                ('Administrator_Name', models.CharField(max_length=70)),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Contact_Number', models.CharField(max_length=10)),
                ('Certificate', models.FileField(blank=True, null=True, upload_to='media/certificates/college/')),
                ('Flag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RankList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Rank', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('Student_ID', models.IntegerField(unique=True)),
                ('Student_Name', models.CharField(max_length=100)),
                ('Student_DOB', models.DateField()),
                ('Student_Mark', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Email_ID', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('Student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Address', models.TextField()),
                ('Fathers_Name', models.CharField(max_length=100)),
                ('Mothers_Name', models.CharField(max_length=100)),
                ('Aadhar_Card', models.FileField(blank=True, null=True, upload_to='media/aadhar/')),
                ('School_Name', models.CharField(max_length=100)),
                ('Board_12th', models.CharField(choices=[('CBSE', 'Central Board of Secondary Education (CBSE)'), ('CISCE', 'Council for the Indian School Certificate Examinations (CISCE)'), ('NIOS', 'National Institute of Open Schooling (NIOS)'), ('MSBSHSE', 'Maharashtra State Board of Secondary and Higher Secondary Education (MSBSHSE)'), ('TNBHSE', 'Tamil Nadu State Board of Higher Secondary Education (TNBHSE)'), ('UPMSP', 'Uttar Pradesh Madhyamik Shiksha Parishad (UPMSP)')], max_length=50)),
                ('Certificate_12th', models.FileField(blank=True, null=True, upload_to='media/certificates/12th/')),
                ('Maths_Marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), pages.models.validate_marks])),
                ('Physics_Marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), pages.models.validate_marks])),
                ('Chemistry_Marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), pages.models.validate_marks])),
                ('Cut_Off_Marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(200), pages.models.validate_cutoff])),
                ('Board_10th', models.CharField(choices=[('CBSE', 'Central Board of Secondary Education (CBSE)'), ('CISCE', 'Council for the Indian School Certificate Examinations (CISCE)'), ('NIOS', 'National Institute of Open Schooling (NIOS)'), ('MSBSHSE', 'Maharashtra State Board of Secondary and Higher Secondary Education (MSBSHSE)'), ('TNBSE', 'Tamil Nadu State Board of Secondary Education (TNBSE)'), ('UPMSP', 'Uttar Pradesh Madhyamik Shiksha Parishad (UPMSP)')], max_length=50)),
                ('Certificate_10th', models.FileField(blank=True, null=True, upload_to='media/certificates/10th/')),
                ('TC', models.FileField(blank=True, null=True, upload_to='tc/')),
                ('Passport_Photo', models.ImageField(blank=True, null=True, upload_to='media/photos/')),
                ('Rank', models.IntegerField(blank=True, null=True)),
                ('Allotted_College', models.CharField(blank=True, max_length=100)),
                ('Allotted_Course', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeatMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College_ID', models.IntegerField()),
                ('College_Name', models.CharField(max_length=100)),
                ('Program', models.CharField(choices=[('BE CSE', 'BE Computer Science and Engineering'), ('BTECH IT', 'BTech Information Technology')], max_length=50)),
                ('Seats_Available', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('College_ID', 'Program')},
            },
        ),
        migrations.CreateModel(
            name='ChoiceListTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Rank', models.IntegerField()),
                ('Student_ID', models.IntegerField()),
                ('Program', models.CharField(choices=[('BE CSE', 'BE Computer Science and Engineering'), ('BTECH IT', 'BTech Information Technology')], max_length=50)),
                ('Choice_Number', models.IntegerField(default=0)),
                ('College', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.seatmatrix')),
            ],
        ),
    ]
