# Generated by Django 3.2.18 on 2024-05-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20240513_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='School_Name_10th',
        ),
        migrations.RemoveField(
            model_name='student',
            name='School_Name_12th',
        ),
        migrations.AddField(
            model_name='student',
            name='School_Name10th',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='School_Name12th',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
