# Generated by Django 3.2.18 on 2024-05-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20240513_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tenth_year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
