# Generated by Django 3.2.18 on 2024-05-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20240513_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Allotted_College',
            field=models.CharField(blank=True, default='TBD', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Allotted_Course',
            field=models.CharField(blank=True, default='TBD', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
