# Generated by Django 3.2.18 on 2024-05-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20240513_1648'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatmatrix',
            unique_together=set(),
        ),
    ]
