# Generated by Django 3.2.18 on 2024-05-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_seatmatrix_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Allow_Register', models.IntegerField()),
                ('Allow_CF', models.IntegerField()),
                ('Allow_SM', models.IntegerField()),
                ('Allow_CRL', models.IntegerField()),
            ],
        ),
    ]
