# Generated by Django 3.2.18 on 2024-05-15 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranklist',
            old_name='Student_DOB',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='ranklist',
            old_name='Student_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='ranklist',
            old_name='Student_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='ranklist',
            old_name='Student_Rank',
            new_name='Rank',
        ),
        migrations.RemoveField(
            model_name='ranklist',
            name='Student_Mark',
        ),
        migrations.AddField(
            model_name='ranklist',
            name='Chemistry_Marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='ranklist',
            name='Cut_Off_Marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='ranklist',
            name='Fathers_Name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranklist',
            name='Maths_Marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='ranklist',
            name='Physics_Marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
