# Generated by Django 3.2.18 on 2024-05-15 16:17

import django.core.validators
from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20240515_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranklist',
            name='Chemistry_Marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), pages.models.validate_marks]),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='Cut_Off_Marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(200), pages.models.validate_cutoff]),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='Maths_Marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), pages.models.validate_marks]),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='Physics_Marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), pages.models.validate_marks]),
        ),
    ]
