# Generated by Django 3.2.18 on 2024-05-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_set_allow_create_crl'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatmatrix',
            name='Allow_Login',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
