# Generated by Django 3.2.18 on 2024-05-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_seatmatrix_allow_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatmatrix',
            name='Allow_Login',
        ),
        migrations.AddField(
            model_name='student',
            name='Allow_Login',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
