# Generated by Django 3.2.18 on 2024-05-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20240519_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='Allot_Program',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='Show_Allotted',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
