# Generated by Django 3.2.18 on 2024-05-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20240519_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='Log_Stat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Log_Stat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choicelisttable',
            name='Choice_Number',
            field=models.IntegerField(),
        ),
    ]
