# Generated by Django 3.2.18 on 2024-05-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_aadhar_marksheets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadhar',
            old_name='Number',
            new_name='Aadhar_Number',
        ),
        migrations.AddField(
            model_name='aadhar',
            name='QR_Number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheets',
            name='QR_Number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
