# Generated by Django 3.2.18 on 2024-05-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_aadhar_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serv_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual', models.FileField(blank=True, null=True, upload_to='media/serverfiles/')),
            ],
        ),
    ]
