# Generated by Django 3.2.18 on 2024-06-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
