# Generated by Django 3.2.18 on 2024-06-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20240616_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='College_Image',
        ),
        migrations.AddField(
            model_name='institute',
            name='College_Image_URL',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
