# Generated by Django 3.2.18 on 2024-06-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20240616_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='DelRecords',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='Finish',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='ReAllot',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
