# Generated by Django 3.2.18 on 2024-06-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_student_allot_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Choice_Number',
            field=models.IntegerField(default=0),
        ),
    ]
