# Generated by Django 3.2.18 on 2024-06-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
